deployments:
- name: ml-bst-movielens1m-recommender-training
  version: 1.0.0
  tags: ["test","recommender"]
  description: "Deployment of the MovieLens 1M Recommender Training pipeline"
  schedule: {}
  flow_name: "ml-bst-movielens1m-recommender-training-flow"
  entrypoint: train.py:bst_movielens1m_recommender_training_pipeline
  parameters: 
    artifact_dir: "artifacts"
    model_save_dir: "models"
    env: "test"
    sequence_length: 9
    test_size: 0.85
    genres_length: 4
    embedding_dim: 128
    dropout: 0.3
    epoches: 1
    learning_rate: 0.001
    batch_size: 256
  work_pool:
    name: zooncamp-work-pool
    work_queue_name: default
    job_variable:
      image: bst-movielens1m-recommender-training-pipeline